// AUTO-GENERATED by scripts/gen-db-types.mjs (pnpm db:types). Do not edit by hand.
// Introspected over DATABASE_URL_RO — read-only, information_schema/pg_catalog only.
//
// 2026-09-29: school_events (new table) and school_posts' post_code/slug/tier/
// requested_tier/listing_* columns, plus the post_tier and school_event_type
// enums, were added by hand to match supabase/migrations/
// 20260929050000_events_and_news_depth.sql. school_jobs (new table) and the
// job_employment_type enum were likewise added by hand to match
// 20260929060000_school_jobs.sql, and admission_leads (new table) plus the
// admission_lead_status enum to match 20260929070000_admission_leads.sql.
// A 4th round (same day, Activity & Admissions Consolidation increment) added
// by hand to match 20260929090000_activity_admissions_v1.sql: rejection_reason
// on school_posts/school_events/school_jobs, withdrawn_at on school_posts, and
// the new analytics_events table.
// 30 Sep 2026 (Admission notices -> admission_cycles gap): admission_status
// was missing two values the live enum actually has — `postponed` and
// `cancelled` (confirmed directly against the production enum via
// `select enumlabel from pg_enum where enumtypid = 'admission_status'::regtype`,
// which also matches src/lib/database.types.ts, the separately-generated
// Supabase-MCP types file). Added by hand, same as every other round below.
// DATABASE_URL_RO isn't set in this sandbox, so `pnpm db:types` couldn't
// regenerate from the live schema any of those times. Re-run `pnpm db:types`
// the next time DATABASE_URL_RO is available to confirm this matches and let
// this note go away.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      admission_cycles: {
        Row: {
          id: string;
          school_id: string | null;
          exam_id: string | null;
          academic_year: string;
          class_code: string;
          status: Database["public"]["Enums"]["admission_status"];
          form_mode: Database["public"]["Enums"]["form_mode"];
          opens_on: string | null;
          closes_on: string | null;
          results_on: string | null;
          dob_from: string | null;
          dob_to: string | null;
          registration_fee: number | null;
          late_fee_amount: number | null;
          documents_required: string[] | null;
          form_url: string | null;
          notice_url: string | null;
          eligibility_notes_en: string | null;
          eligibility_notes_hi: string | null;
          selection_notes: string | null;
          pattern: Json | null;
          syllabus: Json | null;
          application_steps: Json | null;
          corrections: Json | null;
          seats_total: number | null;
          verification: Database["public"]["Enums"]["verification_status"];
          source_type: Database["public"]["Enums"]["provenance_source_type"];
          verification_status: Database["public"]["Enums"]["verification_status_v2"];
          last_checked_at: string | null;
          verified_at: string | null;
          verified_by: string | null;
          updated_at: string;
          class_label_ambiguous: boolean;
          class_label_note: string | null;
        };
        Insert: {
          id?: string;
          school_id?: string | null;
          exam_id?: string | null;
          academic_year: string;
          class_code: string;
          status?: Database["public"]["Enums"]["admission_status"];
          form_mode?: Database["public"]["Enums"]["form_mode"];
          opens_on?: string | null;
          closes_on?: string | null;
          results_on?: string | null;
          dob_from?: string | null;
          dob_to?: string | null;
          registration_fee?: number | null;
          late_fee_amount?: number | null;
          documents_required?: string[] | null;
          form_url?: string | null;
          notice_url?: string | null;
          eligibility_notes_en?: string | null;
          eligibility_notes_hi?: string | null;
          selection_notes?: string | null;
          pattern?: Json | null;
          syllabus?: Json | null;
          application_steps?: Json | null;
          corrections?: Json | null;
          seats_total?: number | null;
          verification?: Database["public"]["Enums"]["verification_status"];
          source_type: Database["public"]["Enums"]["provenance_source_type"];
          verification_status: Database["public"]["Enums"]["verification_status_v2"];
          last_checked_at?: string | null;
          verified_at?: string | null;
          verified_by?: string | null;
          updated_at?: string;
          class_label_ambiguous?: boolean;
          class_label_note?: string | null;
        };
        Update: {
          id?: string;
          school_id?: string | null;
          exam_id?: string | null;
          academic_year?: string;
          class_code?: string;
          status?: Database["public"]["Enums"]["admission_status"];
          form_mode?: Database["public"]["Enums"]["form_mode"];
          opens_on?: string | null;
          closes_on?: string | null;
          results_on?: string | null;
          dob_from?: string | null;
          dob_to?: string | null;
          registration_fee?: number | null;
          late_fee_amount?: number | null;
          documents_required?: string[] | null;
          form_url?: string | null;
          notice_url?: string | null;
          eligibility_notes_en?: string | null;
          eligibility_notes_hi?: string | null;
          selection_notes?: string | null;
          pattern?: Json | null;
          syllabus?: Json | null;
          application_steps?: Json | null;
          corrections?: Json | null;
          seats_total?: number | null;
          verification?: Database["public"]["Enums"]["verification_status"];
          source_type?: Database["public"]["Enums"]["provenance_source_type"];
          verification_status?: Database["public"]["Enums"]["verification_status_v2"];
          last_checked_at?: string | null;
          verified_at?: string | null;
          verified_by?: string | null;
          updated_at?: string;
          class_label_ambiguous?: boolean;
          class_label_note?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "admission_cycles_class_code_fkey";
            columns: ["class_code"];
            isOneToOne: false;
            referencedRelation: "class_levels";
            referencedColumns: ["code"];
          },
          {
            foreignKeyName: "admission_cycles_exam_id_fkey";
            columns: ["exam_id"];
            isOneToOne: false;
            referencedRelation: "exams";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "admission_cycles_school_id_fkey";
            columns: ["school_id"];
            isOneToOne: false;
            referencedRelation: "schools";
            referencedColumns: ["id"];
          },
        ];
      };
      admission_leads: {
        Row: {
          id: string;
          school_id: string;
          admission_cycle_id: string;
          class_code: string;
          academic_year: string;
          user_id: string;
          full_name: string | null;
          phone: string | null;
          note: string | null;
          consent_at: string;
          status: Database["public"]["Enums"]["admission_lead_status"];
          status_updated_by: string | null;
          status_updated_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          school_id: string;
          admission_cycle_id: string;
          class_code: string;
          academic_year: string;
          user_id: string;
          full_name?: string | null;
          phone?: string | null;
          note?: string | null;
          consent_at?: string;
          status?: Database["public"]["Enums"]["admission_lead_status"];
          status_updated_by?: string | null;
          status_updated_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          school_id?: string;
          admission_cycle_id?: string;
          class_code?: string;
          academic_year?: string;
          user_id?: string;
          full_name?: string | null;
          phone?: string | null;
          note?: string | null;
          consent_at?: string;
          status?: Database["public"]["Enums"]["admission_lead_status"];
          status_updated_by?: string | null;
          status_updated_at?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      admission_notices: {
        Row: {
          id: string;
          school_id: string | null;
          url: string;
          content_hash: string;
          storage_path: string | null;
          discovered_at: string;
          extraction: Json | null;
          extraction_model: string | null;
          extraction_confidence: number | null;
          review: Database["public"]["Enums"]["review_status"];
          reviewed_by: string | null;
          reviewed_at: string | null;
          contains_personal_data: boolean;
          retention_note: string | null;
          page_kind: string | null;
          ai_extraction: Json | null;
          promoted_to_golden: boolean;
        };
        Insert: {
          id?: string;
          school_id?: string | null;
          url: string;
          content_hash: string;
          storage_path?: string | null;
          discovered_at?: string;
          extraction?: Json | null;
          extraction_model?: string | null;
          extraction_confidence?: number | null;
          review?: Database["public"]["Enums"]["review_status"];
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          contains_personal_data?: boolean;
          retention_note?: string | null;
          page_kind?: string | null;
          ai_extraction?: Json | null;
          promoted_to_golden?: boolean;
        };
        Update: {
          id?: string;
          school_id?: string | null;
          url?: string;
          content_hash?: string;
          storage_path?: string | null;
          discovered_at?: string;
          extraction?: Json | null;
          extraction_model?: string | null;
          extraction_confidence?: number | null;
          review?: Database["public"]["Enums"]["review_status"];
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          contains_personal_data?: boolean;
          retention_note?: string | null;
          page_kind?: string | null;
          ai_extraction?: Json | null;
          promoted_to_golden?: boolean;
        };
        Relationships: [];
      };
      alert_deliveries: {
        Row: {
          id: number;
          subscription_id: string | null;
          admission_cycle_id: string | null;
          kind: string;
          template: string | null;
          provider_message_id: string | null;
          sent_at: string | null;
          delivered_at: string | null;
          clicked_at: string | null;
          failed_reason: string | null;
        };
        Insert: {
          id?: number;
          subscription_id?: string | null;
          admission_cycle_id?: string | null;
          kind: string;
          template?: string | null;
          provider_message_id?: string | null;
          sent_at?: string | null;
          delivered_at?: string | null;
          clicked_at?: string | null;
          failed_reason?: string | null;
        };
        Update: {
          id?: number;
          subscription_id?: string | null;
          admission_cycle_id?: string | null;
          kind?: string;
          template?: string | null;
          provider_message_id?: string | null;
          sent_at?: string | null;
          delivered_at?: string | null;
          clicked_at?: string | null;
          failed_reason?: string | null;
        };
        Relationships: [];
      };
      alert_subscriptions: {
        Row: {
          id: string;
          user_id: string | null;
          phone: string;
          city_id: number;
          class_codes: string[];
          school_ids: string[];
          whatsapp_opt_in_at: string | null;
          language: string;
          active: boolean;
          utm: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          phone: string;
          city_id: number;
          class_codes?: string[];
          school_ids?: string[];
          whatsapp_opt_in_at?: string | null;
          language?: string;
          active?: boolean;
          utm?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          phone?: string;
          city_id?: number;
          class_codes?: string[];
          school_ids?: string[];
          whatsapp_opt_in_at?: string | null;
          language?: string;
          active?: boolean;
          utm?: Json | null;
          created_at?: string;
        };
        Relationships: [];
      };
      analytics_events: {
        Row: {
          id: string;
          event_type: string;
          entity_type: string | null;
          entity_id: string | null;
          school_id: string | null;
          user_id: string | null;
          metadata: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          event_type: string;
          entity_type?: string | null;
          entity_id?: string | null;
          school_id?: string | null;
          user_id?: string | null;
          metadata?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          event_type?: string;
          entity_type?: string | null;
          entity_id?: string | null;
          school_id?: string | null;
          user_id?: string | null;
          metadata?: Json | null;
          created_at?: string;
        };
        Relationships: [];
      };
      application_orders: {
        Row: {
          id: string;
          user_id: string;
          child_id: string;
          product_code: string;
          amount_inr: number;
          status: Database["public"]["Enums"]["order_status"];
          payment_ref: string | null;
          intake: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          child_id: string;
          product_code: string;
          amount_inr: number;
          status?: Database["public"]["Enums"]["order_status"];
          payment_ref?: string | null;
          intake?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          child_id?: string;
          product_code?: string;
          amount_inr?: number;
          status?: Database["public"]["Enums"]["order_status"];
          payment_ref?: string | null;
          intake?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      applications: {
        Row: {
          id: string;
          order_id: string | null;
          school_id: string;
          admission_cycle_id: string | null;
          status: Database["public"]["Enums"]["application_status"];
          school_application_no: string | null;
          submitted_at: string | null;
          next_action: string | null;
          next_action_due: string | null;
          parent_approved_at: string | null;
          notes: string | null;
          updated_at: string;
        };
        Insert: {
          id?: string;
          order_id?: string | null;
          school_id: string;
          admission_cycle_id?: string | null;
          status?: Database["public"]["Enums"]["application_status"];
          school_application_no?: string | null;
          submitted_at?: string | null;
          next_action?: string | null;
          next_action_due?: string | null;
          parent_approved_at?: string | null;
          notes?: string | null;
          updated_at?: string;
        };
        Update: {
          id?: string;
          order_id?: string | null;
          school_id?: string;
          admission_cycle_id?: string | null;
          status?: Database["public"]["Enums"]["application_status"];
          school_application_no?: string | null;
          submitted_at?: string | null;
          next_action?: string | null;
          next_action_due?: string | null;
          parent_approved_at?: string | null;
          notes?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      audit_log: {
        Row: {
          id: number;
          actor: string | null;
          actor_role: Database["public"]["Enums"]["user_role"] | null;
          action: string;
          entity_table: string | null;
          entity_id: string | null;
          before: Json | null;
          after: Json | null;
          at: string;
        };
        Insert: {
          id?: number;
          actor?: string | null;
          actor_role?: Database["public"]["Enums"]["user_role"] | null;
          action: string;
          entity_table?: string | null;
          entity_id?: string | null;
          before?: Json | null;
          after?: Json | null;
          at?: string;
        };
        Update: {
          id?: number;
          actor?: string | null;
          actor_role?: Database["public"]["Enums"]["user_role"] | null;
          action?: string;
          entity_table?: string | null;
          entity_id?: string | null;
          before?: Json | null;
          after?: Json | null;
          at?: string;
        };
        Relationships: [];
      };
      boards: {
        Row: {
          id: number;
          code: string;
          name_en: string;
          name_hi: string | null;
        };
        Insert: {
          id?: number;
          code: string;
          name_en: string;
          name_hi?: string | null;
        };
        Update: {
          id?: number;
          code?: string;
          name_en?: string;
          name_hi?: string | null;
        };
        Relationships: [];
      };
      children: {
        Row: {
          id: string;
          parent_id: string;
          first_name: string;
          date_of_birth: string;
          target_year: string | null;
          target_class: string | null;
          current_school_text: string | null;
          city_id: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          parent_id: string;
          first_name: string;
          date_of_birth: string;
          target_year?: string | null;
          target_class?: string | null;
          current_school_text?: string | null;
          city_id?: number | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          parent_id?: string;
          first_name?: string;
          date_of_birth?: string;
          target_year?: string | null;
          target_class?: string | null;
          current_school_text?: string | null;
          city_id?: number | null;
          created_at?: string;
        };
        Relationships: [];
      };
      cities: {
        Row: {
          id: number;
          district_id: number;
          name_en: string;
          name_hi: string | null;
          slug: string;
          centroid: unknown | null;
        };
        Insert: {
          id?: number;
          district_id: number;
          name_en: string;
          name_hi?: string | null;
          slug: string;
          centroid?: unknown | null;
        };
        Update: {
          id?: number;
          district_id?: number;
          name_en?: string;
          name_hi?: string | null;
          slug?: string;
          centroid?: unknown | null;
        };
        Relationships: [];
      };
      class_levels: {
        Row: {
          code: string;
          sort_order: number;
          label_en: string;
          label_hi: string | null;
        };
        Insert: {
          code: string;
          sort_order: number;
          label_en: string;
          label_hi?: string | null;
        };
        Update: {
          code?: string;
          sort_order?: number;
          label_en?: string;
          label_hi?: string | null;
        };
        Relationships: [];
      };
      consents: {
        Row: {
          id: number;
          user_id: string | null;
          phone: string | null;
          purpose: Database["public"]["Enums"]["consent_purpose"];
          notice_version: string;
          granted_at: string;
          withdrawn_at: string | null;
          channel: string;
        };
        Insert: {
          id?: number;
          user_id?: string | null;
          phone?: string | null;
          purpose: Database["public"]["Enums"]["consent_purpose"];
          notice_version: string;
          granted_at?: string;
          withdrawn_at?: string | null;
          channel: string;
        };
        Update: {
          id?: number;
          user_id?: string | null;
          phone?: string | null;
          purpose?: Database["public"]["Enums"]["consent_purpose"];
          notice_version?: string;
          granted_at?: string;
          withdrawn_at?: string | null;
          channel?: string;
        };
        Relationships: [];
      };
      conversations: {
        Row: {
          id: string;
          teacher_id: string;
          initiator_id: string;
          created_at: string;
          last_message_at: string;
        };
        Insert: {
          id?: string;
          teacher_id: string;
          initiator_id: string;
          created_at?: string;
          last_message_at?: string;
        };
        Update: {
          id?: string;
          teacher_id?: string;
          initiator_id?: string;
          created_at?: string;
          last_message_at?: string;
        };
        Relationships: [];
      };
      content_posts: {
        Row: {
          id: string;
          city_id: number | null;
          kind: string;
          language: string;
          payload: Json;
          status: string;
          published_channels: string[] | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          city_id?: number | null;
          kind: string;
          language?: string;
          payload: Json;
          status?: string;
          published_channels?: string[] | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          city_id?: number | null;
          kind?: string;
          language?: string;
          payload?: Json;
          status?: string;
          published_channels?: string[] | null;
          created_at?: string;
        };
        Relationships: [];
      };
      correction_requests: {
        Row: {
          id: string;
          school_id: string | null;
          requester: string;
          kind: string;
          details: string | null;
          status: string;
          created_at: string;
          resolved_at: string | null;
        };
        Insert: {
          id?: string;
          school_id?: string | null;
          requester: string;
          kind: string;
          details?: string | null;
          status?: string;
          created_at?: string;
          resolved_at?: string | null;
        };
        Update: {
          id?: string;
          school_id?: string | null;
          requester?: string;
          kind?: string;
          details?: string | null;
          status?: string;
          created_at?: string;
          resolved_at?: string | null;
        };
        Relationships: [];
      };
      corridors: {
        Row: {
          id: number;
          name: string;
          slug: string;
          aliases: string[];
          centroid: unknown | null;
          name_hi: string | null;
          name_hi_status: string;
        };
        Insert: {
          id?: number;
          name: string;
          slug: string;
          aliases?: string[];
          centroid?: unknown | null;
          name_hi?: string | null;
          name_hi_status?: string;
        };
        Update: {
          id?: number;
          name?: string;
          slug?: string;
          aliases?: string[];
          centroid?: unknown | null;
          name_hi?: string | null;
          name_hi_status?: string;
        };
        Relationships: [];
      };
      data_quality_flags: {
        Row: {
          id: number;
          school_id: string | null;
          source_record_id: number | null;
          rule: string;
          field: string | null;
          detail: string | null;
          resolved: boolean;
          created_at: string;
        };
        Insert: {
          id?: number;
          school_id?: string | null;
          source_record_id?: number | null;
          rule: string;
          field?: string | null;
          detail?: string | null;
          resolved?: boolean;
          created_at?: string;
        };
        Update: {
          id?: number;
          school_id?: string | null;
          source_record_id?: number | null;
          rule?: string;
          field?: string | null;
          detail?: string | null;
          resolved?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      districts: {
        Row: {
          id: number;
          state_id: number;
          name_en: string;
          name_hi: string | null;
          slug: string;
          lgd_code: string | null;
        };
        Insert: {
          id?: number;
          state_id: number;
          name_en: string;
          name_hi?: string | null;
          slug: string;
          lgd_code?: string | null;
        };
        Update: {
          id?: number;
          state_id?: number;
          name_en?: string;
          name_hi?: string | null;
          slug?: string;
          lgd_code?: string | null;
        };
        Relationships: [];
      };
      documents: {
        Row: {
          id: string;
          child_id: string;
          kind: Database["public"]["Enums"]["doc_type"];
          storage_path: string;
          sha256: string;
          uploaded_at: string;
          retain_until: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          child_id: string;
          kind: Database["public"]["Enums"]["doc_type"];
          storage_path: string;
          sha256: string;
          uploaded_at?: string;
          retain_until: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          child_id?: string;
          kind?: Database["public"]["Enums"]["doc_type"];
          storage_path?: string;
          sha256?: string;
          uploaded_at?: string;
          retain_until?: string;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      enquiries: {
        Row: {
          id: string;
          school_id: string;
          user_id: string | null;
          child_id: string | null;
          class_code: string | null;
          message: string | null;
          status: string;
          billable: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          school_id: string;
          user_id?: string | null;
          child_id?: string | null;
          class_code?: string | null;
          message?: string | null;
          status?: string;
          billable?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          school_id?: string;
          user_id?: string | null;
          child_id?: string | null;
          class_code?: string | null;
          message?: string | null;
          status?: string;
          billable?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      events: {
        Row: {
          id: number;
          name: string;
          anon_id: string | null;
          user_id: string | null;
          city_id: number | null;
          school_id: string | null;
          class_code: string | null;
          props: Json | null;
          utm: Json | null;
          at: string;
        };
        Insert: {
          id?: number;
          name: string;
          anon_id?: string | null;
          user_id?: string | null;
          city_id?: number | null;
          school_id?: string | null;
          class_code?: string | null;
          props?: Json | null;
          utm?: Json | null;
          at?: string;
        };
        Update: {
          id?: number;
          name?: string;
          anon_id?: string | null;
          user_id?: string | null;
          city_id?: number | null;
          school_id?: string | null;
          class_code?: string | null;
          props?: Json | null;
          utm?: Json | null;
          at?: string;
        };
        Relationships: [];
      };
      facilities: {
        Row: {
          code: string;
          label_en: string;
          label_hi: string | null;
          category: string | null;
        };
        Insert: {
          code: string;
          label_en: string;
          label_hi?: string | null;
          category?: string | null;
        };
        Update: {
          code?: string;
          label_en?: string;
          label_hi?: string | null;
          category?: string | null;
        };
        Relationships: [];
      };
      featured_placements: {
        Row: {
          id: string;
          school_id: string;
          city_id: number;
          class_codes: string[] | null;
          placement: string;
          starts_on: string;
          ends_on: string;
          label: string;
          order_ref: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          school_id: string;
          city_id: number;
          class_codes?: string[] | null;
          placement: string;
          starts_on: string;
          ends_on: string;
          label?: string;
          order_ref?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          school_id?: string;
          city_id?: number;
          class_codes?: string[] | null;
          placement?: string;
          starts_on?: string;
          ends_on?: string;
          label?: string;
          order_ref?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      fee_items: {
        Row: {
          id: string;
          school_id: string;
          academic_year: string;
          class_code: string | null;
          component: string;
          amount_min: number | null;
          amount_max: number | null;
          frequency: string | null;
          verification: Database["public"]["Enums"]["verification_status"];
          updated_at: string;
        };
        Insert: {
          id?: string;
          school_id: string;
          academic_year: string;
          class_code?: string | null;
          component: string;
          amount_min?: number | null;
          amount_max?: number | null;
          frequency?: string | null;
          verification?: Database["public"]["Enums"]["verification_status"];
          updated_at?: string;
        };
        Update: {
          id?: string;
          school_id?: string;
          academic_year?: string;
          class_code?: string | null;
          component?: string;
          amount_min?: number | null;
          amount_max?: number | null;
          frequency?: string | null;
          verification?: Database["public"]["Enums"]["verification_status"];
          updated_at?: string;
        };
        Relationships: [];
      };
      field_provenance: {
        Row: {
          id: number;
          entity_table: string;
          entity_id: string;
          field: string;
          value: Json | null;
          source_id: number | null;
          source_record_id: number | null;
          evidence_url: string | null;
          verified_by: string | null;
          verified_at: string | null;
          created_at: string;
          licence_class: string;
        };
        Insert: {
          id?: number;
          entity_table: string;
          entity_id: string;
          field: string;
          value?: Json | null;
          source_id?: number | null;
          source_record_id?: number | null;
          evidence_url?: string | null;
          verified_by?: string | null;
          verified_at?: string | null;
          created_at?: string;
          licence_class?: string;
        };
        Update: {
          id?: number;
          entity_table?: string;
          entity_id?: string;
          field?: string;
          value?: Json | null;
          source_id?: number | null;
          source_record_id?: number | null;
          evidence_url?: string | null;
          verified_by?: string | null;
          verified_at?: string | null;
          created_at?: string;
          licence_class?: string;
        };
        Relationships: [];
      };
      form_mappings: {
        Row: {
          id: string;
          school_id: string;
          academic_year: string;
          form_url: string | null;
          mapping: Json;
          notes: string | null;
          updated_at: string;
        };
        Insert: {
          id?: string;
          school_id: string;
          academic_year: string;
          form_url?: string | null;
          mapping: Json;
          notes?: string | null;
          updated_at?: string;
        };
        Update: {
          id?: string;
          school_id?: string;
          academic_year?: string;
          form_url?: string | null;
          mapping?: Json;
          notes?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      invoices: {
        Row: {
          id: string;
          number: string;
          customer_type: string;
          customer_id: string;
          amount_inr: number;
          gst_inr: number;
          gstin: string | null;
          issued_at: string;
          pdf_path: string | null;
        };
        Insert: {
          id?: string;
          number: string;
          customer_type: string;
          customer_id: string;
          amount_inr: number;
          gst_inr: number;
          gstin?: string | null;
          issued_at?: string;
          pdf_path?: string | null;
        };
        Update: {
          id?: string;
          number?: string;
          customer_type?: string;
          customer_id?: string;
          amount_inr?: number;
          gst_inr?: number;
          gstin?: string | null;
          issued_at?: string;
          pdf_path?: string | null;
        };
        Relationships: [];
      };
      landmarks: {
        Row: {
          id: number;
          locality_id: number | null;
          name: string;
          type: string | null;
        };
        Insert: {
          id?: number;
          locality_id?: number | null;
          name: string;
          type?: string | null;
        };
        Update: {
          id?: number;
          locality_id?: number | null;
          name?: string;
          type?: string | null;
        };
        Relationships: [];
      };
      localities: {
        Row: {
          id: number;
          city_id: number;
          name_en: string;
          name_hi: string | null;
          slug: string;
          pincodes: string[] | null;
          centroid: unknown | null;
          notable_landmarks: string[] | null;
          nearby_locality_slugs: string[] | null;
          zone: string | null;
          ward_number: string | null;
          ward_name: string | null;
          character_tags: string[] | null;
          micro_localities: string[] | null;
          description: string | null;
          enrichment_source: string | null;
          aliases: string[];
          parent_locality_id: number | null;
          status: string;
          source: string | null;
          external_ref: string | null;
          name_hi_status: string;
          superseded_by_corridor_id: number | null;
        };
        Insert: {
          id?: number;
          city_id: number;
          name_en: string;
          name_hi?: string | null;
          slug: string;
          pincodes?: string[] | null;
          centroid?: unknown | null;
          notable_landmarks?: string[] | null;
          nearby_locality_slugs?: string[] | null;
          zone?: string | null;
          ward_number?: string | null;
          ward_name?: string | null;
          character_tags?: string[] | null;
          micro_localities?: string[] | null;
          description?: string | null;
          enrichment_source?: string | null;
          aliases?: string[];
          parent_locality_id?: number | null;
          status?: string;
          source?: string | null;
          external_ref?: string | null;
          name_hi_status?: string;
          superseded_by_corridor_id?: number | null;
        };
        Update: {
          id?: number;
          city_id?: number;
          name_en?: string;
          name_hi?: string | null;
          slug?: string;
          pincodes?: string[] | null;
          centroid?: unknown | null;
          notable_landmarks?: string[] | null;
          nearby_locality_slugs?: string[] | null;
          zone?: string | null;
          ward_number?: string | null;
          ward_name?: string | null;
          character_tags?: string[] | null;
          micro_localities?: string[] | null;
          description?: string | null;
          enrichment_source?: string | null;
          aliases?: string[];
          parent_locality_id?: number | null;
          status?: string;
          source?: string | null;
          external_ref?: string | null;
          name_hi_status?: string;
          superseded_by_corridor_id?: number | null;
        };
        Relationships: [];
      };
      locality_corridors: {
        Row: {
          locality_id: number;
          corridor_id: number;
        };
        Insert: {
          locality_id: number;
          corridor_id: number;
        };
        Update: {
          locality_id?: number;
          corridor_id?: number;
        };
        Relationships: [];
      };
      locality_neighbors: {
        Row: {
          locality_id: number;
          neighbor_locality_id: number;
          distance_meters: number | null;
          method: string;
        };
        Insert: {
          locality_id: number;
          neighbor_locality_id: number;
          distance_meters?: number | null;
          method: string;
        };
        Update: {
          locality_id?: number;
          neighbor_locality_id?: number;
          distance_meters?: number | null;
          method?: string;
        };
        Relationships: [];
      };
      locality_pincodes: {
        Row: {
          locality_id: number;
          pincode: string;
        };
        Insert: {
          locality_id: number;
          pincode: string;
        };
        Update: {
          locality_id?: number;
          pincode?: string;
        };
        Relationships: [];
      };
      messages: {
        Row: {
          id: string;
          conversation_id: string;
          sender_id: string;
          body: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          conversation_id: string;
          sender_id: string;
          body: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          conversation_id?: string;
          sender_id?: string;
          body?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      ops_tasks: {
        Row: {
          id: string;
          kind: Database["public"]["Enums"]["task_type"];
          status: Database["public"]["Enums"]["task_status"];
          priority: number;
          school_id: string | null;
          ref_table: string | null;
          ref_id: string | null;
          assignee: string | null;
          due_at: string | null;
          payload: Json | null;
          outcome: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          kind: Database["public"]["Enums"]["task_type"];
          status?: Database["public"]["Enums"]["task_status"];
          priority?: number;
          school_id?: string | null;
          ref_table?: string | null;
          ref_id?: string | null;
          assignee?: string | null;
          due_at?: string | null;
          payload?: Json | null;
          outcome?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          kind?: Database["public"]["Enums"]["task_type"];
          status?: Database["public"]["Enums"]["task_status"];
          priority?: number;
          school_id?: string | null;
          ref_table?: string | null;
          ref_id?: string | null;
          assignee?: string | null;
          due_at?: string | null;
          payload?: Json | null;
          outcome?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      products: {
        Row: {
          code: string;
          name: string;
          price_inr: number;
          gst_rate: number;
          active: boolean;
        };
        Insert: {
          code: string;
          name: string;
          price_inr: number;
          gst_rate?: number;
          active?: boolean;
        };
        Update: {
          code?: string;
          name?: string;
          price_inr?: number;
          gst_rate?: number;
          active?: boolean;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          user_id: string;
          role: Database["public"]["Enums"]["user_role"];
          full_name: string | null;
          phone: string | null;
          email: string | null;
          language: string;
          home_city_id: number | null;
          created_at: string;
        };
        Insert: {
          user_id: string;
          role?: Database["public"]["Enums"]["user_role"];
          full_name?: string | null;
          phone?: string | null;
          email?: string | null;
          language?: string;
          home_city_id?: number | null;
          created_at?: string;
        };
        Update: {
          user_id?: string;
          role?: Database["public"]["Enums"]["user_role"];
          full_name?: string | null;
          phone?: string | null;
          email?: string | null;
          language?: string;
          home_city_id?: number | null;
          created_at?: string;
        };
        Relationships: [];
      };
      rate_limits: {
        Row: {
          key: string;
          count: number;
          window_start: string;
        };
        Insert: {
          key: string;
          count?: number;
          window_start?: string;
        };
        Update: {
          key?: string;
          count?: number;
          window_start?: string;
        };
        Relationships: [];
      };
      sales_accounts: {
        Row: {
          school_id: string;
          stage: string;
          owner: string | null;
          last_contact_at: string | null;
          notes: string | null;
        };
        Insert: {
          school_id: string;
          stage?: string;
          owner?: string | null;
          last_contact_at?: string | null;
          notes?: string | null;
        };
        Update: {
          school_id?: string;
          stage?: string;
          owner?: string | null;
          last_contact_at?: string | null;
          notes?: string | null;
        };
        Relationships: [];
      };
      sales_activities: {
        Row: {
          id: number;
          school_id: string | null;
          actor: string | null;
          kind: string | null;
          outcome: string | null;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: number;
          school_id?: string | null;
          actor?: string | null;
          kind?: string | null;
          outcome?: string | null;
          notes?: string | null;
          created_at?: string;
        };
        Update: {
          id?: number;
          school_id?: string | null;
          actor?: string | null;
          kind?: string | null;
          outcome?: string | null;
          notes?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      schema_migrations: {
        Row: {
          filename: string;
          applied_at: string;
        };
        Insert: {
          filename: string;
          applied_at?: string;
        };
        Update: {
          filename?: string;
          applied_at?: string;
        };
        Relationships: [];
      };
      school_affiliations: {
        Row: {
          id: string;
          school_id: string;
          board_id: number;
          affiliation_no: string | null;
          level: string | null;
          valid_from: string | null;
          valid_to: string | null;
          source_id: number | null;
        };
        Insert: {
          id?: string;
          school_id: string;
          board_id: number;
          affiliation_no?: string | null;
          level?: string | null;
          valid_from?: string | null;
          valid_to?: string | null;
          source_id?: number | null;
        };
        Update: {
          id?: string;
          school_id?: string;
          board_id?: number;
          affiliation_no?: string | null;
          level?: string | null;
          valid_from?: string | null;
          valid_to?: string | null;
          source_id?: number | null;
        };
        Relationships: [];
      };
      school_claims: {
        Row: {
          id: string;
          school_id: string;
          user_id: string;
          method: string;
          evidence: Json | null;
          status: Database["public"]["Enums"]["claim_status"];
          reviewed_by: string | null;
          reviewed_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          school_id: string;
          user_id: string;
          method: string;
          evidence?: Json | null;
          status?: Database["public"]["Enums"]["claim_status"];
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          school_id?: string;
          user_id?: string;
          method?: string;
          evidence?: Json | null;
          status?: Database["public"]["Enums"]["claim_status"];
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      school_facilities: {
        Row: {
          school_id: string;
          facility_code: string;
          available: boolean;
          notes: string | null;
        };
        Insert: {
          school_id: string;
          facility_code: string;
          available: boolean;
          notes?: string | null;
        };
        Update: {
          school_id?: string;
          facility_code?: string;
          available?: boolean;
          notes?: string | null;
        };
        Relationships: [];
      };
      school_identifiers: {
        Row: {
          school_id: string;
          scheme: string;
          value: string;
        };
        Insert: {
          school_id: string;
          scheme: string;
          value: string;
        };
        Update: {
          school_id?: string;
          scheme?: string;
          value?: string;
        };
        Relationships: [];
      };
      school_media: {
        Row: {
          id: string;
          school_id: string;
          kind: string;
          storage_path: string | null;
          external_url: string | null;
          licence: string;
          approved: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          school_id: string;
          kind: string;
          storage_path?: string | null;
          external_url?: string | null;
          licence: string;
          approved?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          school_id?: string;
          kind?: string;
          storage_path?: string | null;
          external_url?: string | null;
          licence?: string;
          approved?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      school_members: {
        Row: {
          school_id: string;
          user_id: string;
          role: Database["public"]["Enums"]["school_member_role"];
        };
        Insert: {
          school_id: string;
          user_id: string;
          role?: Database["public"]["Enums"]["school_member_role"];
        };
        Update: {
          school_id?: string;
          user_id?: string;
          role?: Database["public"]["Enums"]["school_member_role"];
        };
        Relationships: [];
      };
      school_posts: {
        Row: {
          id: string;
          school_id: string;
          kind: Database["public"]["Enums"]["post_kind"];
          title: string;
          body: string;
          source_url: string | null;
          review: Database["public"]["Enums"]["review_status"];
          reviewed_by: string | null;
          reviewed_at: string | null;
          created_by: string | null;
          published_at: string | null;
          created_at: string;
          updated_at: string;
          post_code: number;
          slug: string;
          tier: Database["public"]["Enums"]["post_tier"];
          requested_tier: Database["public"]["Enums"]["post_tier"] | null;
          listing_requested_at: string | null;
          listing_review: Database["public"]["Enums"]["review_status"] | null;
          listing_reviewed_by: string | null;
          listing_reviewed_at: string | null;
          rejection_reason: string | null;
          withdrawn_at: string | null;
        };
        Insert: {
          id?: string;
          school_id: string;
          kind?: Database["public"]["Enums"]["post_kind"];
          title: string;
          body: string;
          source_url?: string | null;
          review?: Database["public"]["Enums"]["review_status"];
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          created_by?: string | null;
          published_at?: string | null;
          created_at?: string;
          updated_at?: string;
          post_code?: number;
          slug?: string;
          tier?: Database["public"]["Enums"]["post_tier"];
          requested_tier?: Database["public"]["Enums"]["post_tier"] | null;
          listing_requested_at?: string | null;
          listing_review?: Database["public"]["Enums"]["review_status"] | null;
          listing_reviewed_by?: string | null;
          listing_reviewed_at?: string | null;
          rejection_reason?: string | null;
          withdrawn_at?: string | null;
        };
        Update: {
          id?: string;
          school_id?: string;
          kind?: Database["public"]["Enums"]["post_kind"];
          title?: string;
          body?: string;
          source_url?: string | null;
          review?: Database["public"]["Enums"]["review_status"];
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          created_by?: string | null;
          published_at?: string | null;
          created_at?: string;
          updated_at?: string;
          post_code?: number;
          slug?: string;
          tier?: Database["public"]["Enums"]["post_tier"];
          requested_tier?: Database["public"]["Enums"]["post_tier"] | null;
          listing_requested_at?: string | null;
          listing_review?: Database["public"]["Enums"]["review_status"] | null;
          listing_reviewed_by?: string | null;
          listing_reviewed_at?: string | null;
          rejection_reason?: string | null;
          withdrawn_at?: string | null;
        };
        Relationships: [];
      };
      school_events: {
        Row: {
          id: string;
          school_id: string;
          event_code: number;
          slug: string;
          event_type: Database["public"]["Enums"]["school_event_type"];
          title: string;
          description: string | null;
          starts_at: string;
          ends_at: string | null;
          location: string | null;
          class_codes: string[];
          registration_url: string | null;
          source_url: string | null;
          cancelled_at: string | null;
          listing_requested_at: string | null;
          listing_review: Database["public"]["Enums"]["review_status"] | null;
          listing_reviewed_by: string | null;
          listing_reviewed_at: string | null;
          rejection_reason: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          school_id: string;
          event_code?: number;
          slug?: string;
          event_type?: Database["public"]["Enums"]["school_event_type"];
          title: string;
          description?: string | null;
          starts_at: string;
          ends_at?: string | null;
          location?: string | null;
          class_codes?: string[];
          registration_url?: string | null;
          source_url?: string | null;
          cancelled_at?: string | null;
          listing_requested_at?: string | null;
          listing_review?: Database["public"]["Enums"]["review_status"] | null;
          listing_reviewed_by?: string | null;
          listing_reviewed_at?: string | null;
          rejection_reason?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          school_id?: string;
          event_code?: number;
          slug?: string;
          event_type?: Database["public"]["Enums"]["school_event_type"];
          title?: string;
          description?: string | null;
          starts_at?: string;
          ends_at?: string | null;
          location?: string | null;
          class_codes?: string[];
          registration_url?: string | null;
          source_url?: string | null;
          cancelled_at?: string | null;
          listing_requested_at?: string | null;
          listing_review?: Database["public"]["Enums"]["review_status"] | null;
          listing_reviewed_by?: string | null;
          listing_reviewed_at?: string | null;
          rejection_reason?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      school_jobs: {
        Row: {
          id: string;
          school_id: string;
          job_code: number;
          slug: string;
          title: string;
          employment_type: Database["public"]["Enums"]["job_employment_type"];
          subject: string | null;
          description: string;
          experience_required: string | null;
          salary_range: string | null;
          location: string | null;
          apply_url: string | null;
          apply_email: string | null;
          class_codes: string[];
          closes_at: string | null;
          filled_at: string | null;
          cancelled_at: string | null;
          listing_requested_at: string | null;
          listing_review: Database["public"]["Enums"]["review_status"] | null;
          listing_reviewed_by: string | null;
          listing_reviewed_at: string | null;
          rejection_reason: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          school_id: string;
          job_code?: number;
          slug?: string;
          title: string;
          employment_type?: Database["public"]["Enums"]["job_employment_type"];
          subject?: string | null;
          description: string;
          experience_required?: string | null;
          salary_range?: string | null;
          location?: string | null;
          apply_url?: string | null;
          apply_email?: string | null;
          class_codes?: string[];
          closes_at?: string | null;
          filled_at?: string | null;
          cancelled_at?: string | null;
          listing_requested_at?: string | null;
          listing_review?: Database["public"]["Enums"]["review_status"] | null;
          listing_reviewed_by?: string | null;
          listing_reviewed_at?: string | null;
          rejection_reason?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          school_id?: string;
          job_code?: number;
          slug?: string;
          title?: string;
          employment_type?: Database["public"]["Enums"]["job_employment_type"];
          subject?: string | null;
          description?: string;
          experience_required?: string | null;
          salary_range?: string | null;
          location?: string | null;
          apply_url?: string | null;
          apply_email?: string | null;
          class_codes?: string[];
          closes_at?: string | null;
          filled_at?: string | null;
          cancelled_at?: string | null;
          listing_requested_at?: string | null;
          listing_review?: Database["public"]["Enums"]["review_status"] | null;
          listing_reviewed_by?: string | null;
          listing_reviewed_at?: string | null;
          rejection_reason?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      school_slug_history: {
        Row: {
          school_id: string;
          city_slug: string;
          old_slug: string;
          changed_at: string;
        };
        Insert: {
          school_id: string;
          city_slug: string;
          old_slug: string;
          changed_at?: string;
        };
        Update: {
          school_id?: string;
          city_slug?: string;
          old_slug?: string;
          changed_at?: string;
        };
        Relationships: [];
      };
      school_teacher_affiliations: {
        Row: {
          id: string;
          school_id: string;
          teacher_id: string;
          status: Database["public"]["Enums"]["affiliation_status"];
          initiated_by: string;
          requested_by: string | null;
          responded_by: string | null;
          responded_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          school_id: string;
          teacher_id: string;
          status: Database["public"]["Enums"]["affiliation_status"];
          initiated_by: string;
          requested_by?: string | null;
          responded_by?: string | null;
          responded_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          school_id?: string;
          teacher_id?: string;
          status?: Database["public"]["Enums"]["affiliation_status"];
          initiated_by?: string;
          requested_by?: string | null;
          responded_by?: string | null;
          responded_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      schools: {
        Row: {
          id: string;
          slug: string;
          city_id: number | null;
          locality_id: number | null;
          district_id: number | null;
          name_en: string;
          name_hi: string | null;
          name_search: unknown | null;
          management: Database["public"]["Enums"]["school_management"] | null;
          gender: Database["public"]["Enums"]["school_gender"] | null;
          medium: string[] | null;
          min_class: string | null;
          max_class: string | null;
          address: string | null;
          pincode: string | null;
          location: unknown | null;
          geocode_precision: string | null;
          website: string | null;
          phone: string[] | null;
          email: string[] | null;
          established_year: number | null;
          tier: Database["public"]["Enums"]["school_tier"];
          status: Database["public"]["Enums"]["record_status"];
          verification: Database["public"]["Enums"]["verification_status"];
          claim: Database["public"]["Enums"]["claim_status"];
          completeness: number;
          last_verified_at: string | null;
          next_check_due: string | null;
          about_en: string | null;
          about_hi: string | null;
          created_at: string;
          updated_at: string;
          edudel_zone: string | null;
          corridor_id: number | null;
          locality_assignment_method: string | null;
          locality_assignment_note: string | null;
          school_code: number;
          source_type: Database["public"]["Enums"]["provenance_source_type"];
          verification_status: Database["public"]["Enums"]["verification_status_v2"];
          udise_code: string | null;
          principal_name: string | null;
          address_street: string | null;
          address_area: string | null;
          address_city: string | null;
          address_district: string | null;
          address_state: string | null;
          address_state_code: string | null;
          address_pincode: string | null;
          address_source: string | null;
          enriched_at: string | null;
          enrichment_sources: string[] | null;
          data_quality_flags: Json | null;
        };
        Insert: {
          id?: string;
          slug: string;
          city_id?: number | null;
          locality_id?: number | null;
          district_id?: number | null;
          name_en: string;
          name_hi?: string | null;
          name_search?: unknown | null;
          management?: Database["public"]["Enums"]["school_management"] | null;
          gender?: Database["public"]["Enums"]["school_gender"] | null;
          medium?: string[] | null;
          min_class?: string | null;
          max_class?: string | null;
          address?: string | null;
          pincode?: string | null;
          location?: unknown | null;
          geocode_precision?: string | null;
          website?: string | null;
          phone?: string[] | null;
          email?: string[] | null;
          established_year?: number | null;
          tier?: Database["public"]["Enums"]["school_tier"];
          status?: Database["public"]["Enums"]["record_status"];
          verification?: Database["public"]["Enums"]["verification_status"];
          claim?: Database["public"]["Enums"]["claim_status"];
          completeness?: number;
          last_verified_at?: string | null;
          next_check_due?: string | null;
          about_en?: string | null;
          about_hi?: string | null;
          created_at?: string;
          updated_at?: string;
          edudel_zone?: string | null;
          corridor_id?: number | null;
          locality_assignment_method?: string | null;
          locality_assignment_note?: string | null;
          school_code?: number;
          source_type: Database["public"]["Enums"]["provenance_source_type"];
          verification_status: Database["public"]["Enums"]["verification_status_v2"];
          udise_code?: string | null;
          principal_name?: string | null;
          address_street?: string | null;
          address_area?: string | null;
          address_city?: string | null;
          address_district?: string | null;
          address_state?: string | null;
          address_state_code?: string | null;
          address_pincode?: string | null;
          address_source?: string | null;
          enriched_at?: string | null;
          enrichment_sources?: string[] | null;
          data_quality_flags?: Json | null;
        };
        Update: {
          id?: string;
          slug?: string;
          city_id?: number | null;
          locality_id?: number | null;
          district_id?: number | null;
          name_en?: string;
          name_hi?: string | null;
          name_search?: unknown | null;
          management?: Database["public"]["Enums"]["school_management"] | null;
          gender?: Database["public"]["Enums"]["school_gender"] | null;
          medium?: string[] | null;
          min_class?: string | null;
          max_class?: string | null;
          address?: string | null;
          pincode?: string | null;
          location?: unknown | null;
          geocode_precision?: string | null;
          website?: string | null;
          phone?: string[] | null;
          email?: string[] | null;
          established_year?: number | null;
          tier?: Database["public"]["Enums"]["school_tier"];
          status?: Database["public"]["Enums"]["record_status"];
          verification?: Database["public"]["Enums"]["verification_status"];
          claim?: Database["public"]["Enums"]["claim_status"];
          completeness?: number;
          last_verified_at?: string | null;
          next_check_due?: string | null;
          about_en?: string | null;
          about_hi?: string | null;
          created_at?: string;
          updated_at?: string;
          edudel_zone?: string | null;
          corridor_id?: number | null;
          locality_assignment_method?: string | null;
          locality_assignment_note?: string | null;
          school_code?: number;
          source_type?: Database["public"]["Enums"]["provenance_source_type"];
          verification_status?: Database["public"]["Enums"]["verification_status_v2"];
          udise_code?: string | null;
          principal_name?: string | null;
          address_street?: string | null;
          address_area?: string | null;
          address_city?: string | null;
          address_district?: string | null;
          address_state?: string | null;
          address_state_code?: string | null;
          address_pincode?: string | null;
          address_source?: string | null;
          enriched_at?: string | null;
          enrichment_sources?: string[] | null;
          data_quality_flags?: Json | null;
        };
        Relationships: [];
      };
      seat_status: {
        Row: {
          id: string;
          school_id: string;
          academic_year: string;
          class_code: string;
          public_status: Database["public"]["Enums"]["seat_public_status"];
          range_label: string | null;
          exact_count: number | null;
          confidence: Database["public"]["Enums"]["seat_confidence"];
          mid_session_accepted: boolean | null;
          reported_via: string | null;
          reported_at: string;
          confirmed_at: string | null;
        };
        Insert: {
          id?: string;
          school_id: string;
          academic_year: string;
          class_code: string;
          public_status: Database["public"]["Enums"]["seat_public_status"];
          range_label?: string | null;
          exact_count?: number | null;
          confidence: Database["public"]["Enums"]["seat_confidence"];
          mid_session_accepted?: boolean | null;
          reported_via?: string | null;
          reported_at?: string;
          confirmed_at?: string | null;
        };
        Update: {
          id?: string;
          school_id?: string;
          academic_year?: string;
          class_code?: string;
          public_status?: Database["public"]["Enums"]["seat_public_status"];
          range_label?: string | null;
          exact_count?: number | null;
          confidence?: Database["public"]["Enums"]["seat_confidence"];
          mid_session_accepted?: boolean | null;
          reported_via?: string | null;
          reported_at?: string;
          confirmed_at?: string | null;
        };
        Relationships: [];
      };
      shortlists: {
        Row: {
          user_id: string;
          school_id: string;
          child_id: string | null;
          created_at: string;
        };
        Insert: {
          user_id: string;
          school_id: string;
          child_id?: string | null;
          created_at?: string;
        };
        Update: {
          user_id?: string;
          school_id?: string;
          child_id?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      source_records: {
        Row: {
          id: number;
          source_id: number;
          external_id: string;
          payload: Json;
          content_hash: string;
          fetched_at: string;
          matched_school_id: string | null;
          match_confidence: number | null;
          match_method: string | null;
        };
        Insert: {
          id?: number;
          source_id: number;
          external_id: string;
          payload: Json;
          content_hash: string;
          fetched_at?: string;
          matched_school_id?: string | null;
          match_confidence?: number | null;
          match_method?: string | null;
        };
        Update: {
          id?: number;
          source_id?: number;
          external_id?: string;
          payload?: Json;
          content_hash?: string;
          fetched_at?: string;
          matched_school_id?: string | null;
          match_confidence?: number | null;
          match_method?: string | null;
        };
        Relationships: [];
      };
      sources: {
        Row: {
          id: number;
          code: string;
          name: string;
          base_url: string | null;
          licence_note: string | null;
          trust_rank: number;
        };
        Insert: {
          id?: number;
          code: string;
          name: string;
          base_url?: string | null;
          licence_note?: string | null;
          trust_rank?: number;
        };
        Update: {
          id?: number;
          code?: string;
          name?: string;
          base_url?: string | null;
          licence_note?: string | null;
          trust_rank?: number;
        };
        Relationships: [];
      };
      states: {
        Row: {
          id: number;
          code: string;
          name_en: string;
          name_hi: string | null;
          slug: string;
        };
        Insert: {
          id?: number;
          code: string;
          name_en: string;
          name_hi?: string | null;
          slug: string;
        };
        Update: {
          id?: number;
          code?: string;
          name_en?: string;
          name_hi?: string | null;
          slug?: string;
        };
        Relationships: [];
      };
      teacher_claims: {
        Row: {
          id: string;
          teacher_id: string;
          user_id: string;
          method: string;
          evidence: Json | null;
          status: Database["public"]["Enums"]["claim_status"];
          reviewed_by: string | null;
          reviewed_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          teacher_id: string;
          user_id: string;
          method: string;
          evidence?: Json | null;
          status?: Database["public"]["Enums"]["claim_status"];
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          teacher_id?: string;
          user_id?: string;
          method?: string;
          evidence?: Json | null;
          status?: Database["public"]["Enums"]["claim_status"];
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      teacher_experience: {
        Row: {
          id: string;
          teacher_id: string;
          role_title: string;
          school_id: string | null;
          school_text: string | null;
          start_year: number;
          end_year: number | null;
          sort_order: number;
        };
        Insert: {
          id?: string;
          teacher_id: string;
          role_title: string;
          school_id?: string | null;
          school_text?: string | null;
          start_year: number;
          end_year?: number | null;
          sort_order?: number;
        };
        Update: {
          id?: string;
          teacher_id?: string;
          role_title?: string;
          school_id?: string | null;
          school_text?: string | null;
          start_year?: number;
          end_year?: number | null;
          sort_order?: number;
        };
        Relationships: [];
      };
      teacher_qualifications: {
        Row: {
          id: string;
          teacher_id: string;
          title: string;
          detail: string | null;
          verified_by: string | null;
          verified_at: string | null;
        };
        Insert: {
          id?: string;
          teacher_id: string;
          title: string;
          detail?: string | null;
          verified_by?: string | null;
          verified_at?: string | null;
        };
        Update: {
          id?: string;
          teacher_id?: string;
          title?: string;
          detail?: string | null;
          verified_by?: string | null;
          verified_at?: string | null;
        };
        Relationships: [];
      };
      teachers: {
        Row: {
          teacher_code: number;
          id: string;
          claimed_by: string | null;
          full_name: string;
          subject: string | null;
          level: string | null;
          primary_school_id: string | null;
          locality_id: number | null;
          headline: string | null;
          about: string | null;
          years_teaching: number | null;
          open_to: string[];
          photo_storage_path: string | null;
          is_listed: boolean;
          status: Database["public"]["Enums"]["record_status"];
          created_at: string;
          updated_at: string;
          slug: string;
        };
        Insert: {
          teacher_code?: number;
          id?: string;
          claimed_by?: string | null;
          full_name: string;
          subject?: string | null;
          level?: string | null;
          primary_school_id?: string | null;
          locality_id?: number | null;
          headline?: string | null;
          about?: string | null;
          years_teaching?: number | null;
          open_to?: string[];
          photo_storage_path?: string | null;
          is_listed?: boolean;
          status?: Database["public"]["Enums"]["record_status"];
          created_at?: string;
          updated_at?: string;
          slug: string;
        };
        Update: {
          teacher_code?: number;
          id?: string;
          claimed_by?: string | null;
          full_name?: string;
          subject?: string | null;
          level?: string | null;
          primary_school_id?: string | null;
          locality_id?: number | null;
          headline?: string | null;
          about?: string | null;
          years_teaching?: number | null;
          open_to?: string[];
          photo_storage_path?: string | null;
          is_listed?: boolean;
          status?: Database["public"]["Enums"]["record_status"];
          created_at?: string;
          updated_at?: string;
          slug?: string;
        };
        Relationships: [];
      };
      update_reports: {
        Row: {
          id: string;
          school_id: string | null;
          reporter_type: string;
          reporter_id: string | null;
          contact: string | null;
          message: string;
          attachment_path: string | null;
          status: Database["public"]["Enums"]["review_status"];
          created_at: string;
        };
        Insert: {
          id?: string;
          school_id?: string | null;
          reporter_type: string;
          reporter_id?: string | null;
          contact?: string | null;
          message: string;
          attachment_path?: string | null;
          status?: Database["public"]["Enums"]["review_status"];
          created_at?: string;
        };
        Update: {
          id?: string;
          school_id?: string | null;
          reporter_type?: string;
          reporter_id?: string | null;
          contact?: string | null;
          message?: string;
          attachment_path?: string | null;
          status?: Database["public"]["Enums"]["review_status"];
          created_at?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      // active_cities dropped 30 Sep 2026 (launch gate removal) — it filtered
      // on cities.is_launch, which was dropped in the same migration
      // (20260930190000_remove_launch_gate_entirely.sql). Confirmed unused in
      // app code before dropping.
    };
    Functions: {
      approve_application: {
        Args: Record<string, unknown>; // p_application_id uuid
        Returns: unknown; // void
      };
      check_rate_limit: {
        Args: Record<string, unknown>; // p_key text, p_max_attempts integer, p_window_seconds integer
        Returns: unknown; // boolean
      };
      create_application_order: {
        Args: Record<string, unknown>; // p_product_code text, p_child_id uuid
        Returns: unknown; // uuid
      };
      current_role_is: {
        Args: Record<string, unknown>; // r user_role
        Returns: unknown; // boolean
      };
      current_user_role: {
        Args: Record<string, unknown>; // no args
        Returns: unknown; // user_role
      };
      fuzzy_candidates_in_districts: {
        Args: Record<string, unknown>; // p_district_ids integer[], p_name text, p_limit integer DEFAULT 5
        Returns: unknown; // TABLE(id uuid, name_en text, address text, pincode text, sim real)
      };
      is_school_admin: {
        Args: Record<string, unknown>; // sid uuid
        Returns: unknown; // boolean
      };
      is_school_member: {
        Args: Record<string, unknown>; // sid uuid
        Returns: unknown; // boolean
      };
      is_staff: {
        Args: Record<string, unknown>; // no args
        Returns: unknown; // boolean
      };
      mark_order_paid: {
        Args: Record<string, unknown>; // p_order_id uuid, p_payment_ref text
        Returns: unknown; // void
      };
      normalize_school_name: {
        Args: Record<string, unknown>; // input text
        Returns: unknown; // text
      };
      purge_expired_documents: {
        Args: Record<string, unknown>; // no args
        Returns: unknown; // integer
      };
      saras_fuzzy_candidates: {
        Args: Record<string, unknown>; // p_district_id integer, p_name text, p_limit integer DEFAULT 5
        Returns: unknown; // TABLE(id uuid, name_en text, sim real)
      };
      save_order_intake: {
        Args: Record<string, unknown>; // p_order_id uuid, p_intake jsonb
        Returns: unknown; // void
      };
    };
    Enums: {
      admission_lead_status: "new" | "contacted" | "closed";
      admission_status:
        | "not_announced"
        | "upcoming"
        | "open"
        | "closing_soon"
        | "closed"
        | "results_out"
        | "postponed"
        | "cancelled";
      application_status:
        | "not_started"
        | "preparing"
        | "awaiting_parent_approval"
        | "submitted"
        | "fee_pending"
        | "interview_scheduled"
        | "result_selected"
        | "result_waitlisted"
        | "result_not_selected"
        | "withdrawn";
      affiliation_status:
        | "pending_teacher"
        | "pending_school"
        | "active"
        | "declined_by_teacher"
        | "declined_by_school"
        | "removed";
      claim_status: "unclaimed" | "pending" | "claimed" | "rejected";
      consent_purpose:
        | "account"
        | "child_profile"
        | "whatsapp_alerts"
        | "application_help"
        | "document_storage"
        | "marketing";
      doc_type:
        | "birth_certificate"
        | "photo_child"
        | "photo_parent"
        | "address_proof"
        | "aadhaar_masked"
        | "previous_report_card"
        | "transfer_certificate"
        | "caste_certificate"
        | "income_certificate"
        | "medical"
        | "other";
      form_mode: "online" | "offline" | "both" | "unknown";
      job_employment_type: "full_time" | "part_time" | "contract" | "visiting";
      order_status:
        | "draft"
        | "awaiting_payment"
        | "paid"
        | "in_progress"
        | "completed"
        | "cancelled"
        | "refunded";
      post_kind: "news" | "press";
      post_tier: "organic" | "featured" | "press_release";
      record_status: "draft" | "published" | "hidden" | "closed" | "opt_out";
      review_status: "pending" | "approved" | "edited" | "rejected" | "needs_triage";
      school_event_type:
        | "ptm"
        | "open_house"
        | "admission_test"
        | "sports_day"
        | "cultural"
        | "workshop"
        | "result_day"
        | "holiday"
        | "fee_deadline"
        | "other";
      school_gender: "coed" | "boys" | "girls";
      school_management:
        | "private_unaided"
        | "private_aided"
        | "government"
        | "central_government"
        | "local_body"
        | "other";
      school_member_role: "admin" | "staff";
      school_tier: "A" | "B" | "C";
      seat_confidence: "confirmed" | "reported" | "application_possible";
      seat_public_status: "open" | "limited" | "waitlist" | "closed";
      task_status: "open" | "in_progress" | "blocked" | "done" | "cancelled";
      task_type:
        | "verify_notice"
        | "verify_update"
        | "verify_record"
        | "call_school"
        | "application"
        | "claim_review"
        | "correction_request"
        | "seat_update";
      provenance_source_type:
        | "official"
        | "school_reported"
        | "schooloye_verified"
        | "user_submitted";
      user_role: "parent" | "school_admin" | "ops" | "admin";
      verification_status: "unverified" | "source_verified" | "ops_verified" | "school_verified";
      verification_status_v2: "unknown" | "pending" | "verified" | "conflicting";
    };
    CompositeTypes: Record<string, never>;
  };
};
