// AUTO-GENERATED by scripts/gen-db-types.mjs (pnpm db:types). Do not edit by hand.
// Introspected over DATABASE_URL_RO — read-only, information_schema/pg_catalog only.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      admission_cycles: {
        Row: {
          id: string;
          school_id: string;
          academic_year: string;
          class_code: string;
          status: Database["public"]["Enums"]["admission_status"];
          form_mode: Database["public"]["Enums"]["form_mode"];
          opens_on: string | null;
          closes_on: string | null;
          results_on: string | null;
          dob_from: string | null;
          dob_to: string | null;
          registration_fee: number | null;
          documents_required: string[] | null;
          form_url: string | null;
          notice_url: string | null;
          selection_notes: string | null;
          seats_total: number | null;
          verification: Database["public"]["Enums"]["verification_status"];
          last_checked_at: string | null;
          verified_at: string | null;
          verified_by: string | null;
          updated_at: string;
          class_label_ambiguous: boolean;
          class_label_note: string | null;
        };
        Insert: {
          id?: string;
          school_id: string;
          academic_year: string;
          class_code: string;
          status?: Database["public"]["Enums"]["admission_status"];
          form_mode?: Database["public"]["Enums"]["form_mode"];
          opens_on?: string | null;
          closes_on?: string | null;
          results_on?: string | null;
          dob_from?: string | null;
          dob_to?: string | null;
          registration_fee?: number | null;
          documents_required?: string[] | null;
          form_url?: string | null;
          notice_url?: string | null;
          selection_notes?: string | null;
          seats_total?: number | null;
          verification?: Database["public"]["Enums"]["verification_status"];
          last_checked_at?: string | null;
          verified_at?: string | null;
          verified_by?: string | null;
          updated_at?: string;
          class_label_ambiguous?: boolean;
          class_label_note?: string | null;
        };
        Update: {
          id?: string;
          school_id?: string;
          academic_year?: string;
          class_code?: string;
          status?: Database["public"]["Enums"]["admission_status"];
          form_mode?: Database["public"]["Enums"]["form_mode"];
          opens_on?: string | null;
          closes_on?: string | null;
          results_on?: string | null;
          dob_from?: string | null;
          dob_to?: string | null;
          registration_fee?: number | null;
          documents_required?: string[] | null;
          form_url?: string | null;
          notice_url?: string | null;
          selection_notes?: string | null;
          seats_total?: number | null;
          verification?: Database["public"]["Enums"]["verification_status"];
          last_checked_at?: string | null;
          verified_at?: string | null;
          verified_by?: string | null;
          updated_at?: string;
          class_label_ambiguous?: boolean;
          class_label_note?: string | null;
        };
        Relationships: [];
      };
      admission_notices: {
        Row: {
          id: string;
          school_id: string | null;
          url: string;
          content_hash: string;
          storage_path: string | null;
          discovered_at: string;
          extraction: Json | null;
          extraction_model: string | null;
          extraction_confidence: number | null;
          review: Database["public"]["Enums"]["review_status"];
          reviewed_by: string | null;
          reviewed_at: string | null;
          contains_personal_data: boolean;
          retention_note: string | null;
          page_kind: string | null;
          ai_extraction: Json | null;
          promoted_to_golden: boolean;
        };
        Insert: {
          id?: string;
          school_id?: string | null;
          url: string;
          content_hash: string;
          storage_path?: string | null;
          discovered_at?: string;
          extraction?: Json | null;
          extraction_model?: string | null;
          extraction_confidence?: number | null;
          review?: Database["public"]["Enums"]["review_status"];
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          contains_personal_data?: boolean;
          retention_note?: string | null;
          page_kind?: string | null;
          ai_extraction?: Json | null;
          promoted_to_golden?: boolean;
        };
        Update: {
          id?: string;
          school_id?: string | null;
          url?: string;
          content_hash?: string;
          storage_path?: string | null;
          discovered_at?: string;
          extraction?: Json | null;
          extraction_model?: string | null;
          extraction_confidence?: number | null;
          review?: Database["public"]["Enums"]["review_status"];
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          contains_personal_data?: boolean;
          retention_note?: string | null;
          page_kind?: string | null;
          ai_extraction?: Json | null;
          promoted_to_golden?: boolean;
        };
        Relationships: [];
      };
      alert_deliveries: {
        Row: {
          id: number;
          subscription_id: string | null;
          admission_cycle_id: string | null;
          kind: string;
          template: string | null;
          provider_message_id: string | null;
          sent_at: string | null;
          delivered_at: string | null;
          clicked_at: string | null;
          failed_reason: string | null;
        };
        Insert: {
          id?: number;
          subscription_id?: string | null;
          admission_cycle_id?: string | null;
          kind: string;
          template?: string | null;
          provider_message_id?: string | null;
          sent_at?: string | null;
          delivered_at?: string | null;
          clicked_at?: string | null;
          failed_reason?: string | null;
        };
        Update: {
          id?: number;
          subscription_id?: string | null;
          admission_cycle_id?: string | null;
          kind?: string;
          template?: string | null;
          provider_message_id?: string | null;
          sent_at?: string | null;
          delivered_at?: string | null;
          clicked_at?: string | null;
          failed_reason?: string | null;
        };
        Relationships: [];
      };
      alert_subscriptions: {
        Row: {
          id: string;
          user_id: string | null;
          phone: string;
          city_id: number;
          class_codes: string[];
          school_ids: string[];
          whatsapp_opt_in_at: string | null;
          language: string;
          active: boolean;
          utm: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          phone: string;
          city_id: number;
          class_codes?: string[];
          school_ids?: string[];
          whatsapp_opt_in_at?: string | null;
          language?: string;
          active?: boolean;
          utm?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          phone?: string;
          city_id?: number;
          class_codes?: string[];
          school_ids?: string[];
          whatsapp_opt_in_at?: string | null;
          language?: string;
          active?: boolean;
          utm?: Json | null;
          created_at?: string;
        };
        Relationships: [];
      };
      application_orders: {
        Row: {
          id: string;
          user_id: string;
          child_id: string;
          product_code: string;
          amount_inr: number;
          status: Database["public"]["Enums"]["order_status"];
          payment_ref: string | null;
          intake: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          child_id: string;
          product_code: string;
          amount_inr: number;
          status?: Database["public"]["Enums"]["order_status"];
          payment_ref?: string | null;
          intake?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          child_id?: string;
          product_code?: string;
          amount_inr?: number;
          status?: Database["public"]["Enums"]["order_status"];
          payment_ref?: string | null;
          intake?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      applications: {
        Row: {
          id: string;
          order_id: string | null;
          school_id: string;
          admission_cycle_id: string | null;
          status: Database["public"]["Enums"]["application_status"];
          school_application_no: string | null;
          submitted_at: string | null;
          next_action: string | null;
          next_action_due: string | null;
          parent_approved_at: string | null;
          notes: string | null;
          updated_at: string;
        };
        Insert: {
          id?: string;
          order_id?: string | null;
          school_id: string;
          admission_cycle_id?: string | null;
          status?: Database["public"]["Enums"]["application_status"];
          school_application_no?: string | null;
          submitted_at?: string | null;
          next_action?: string | null;
          next_action_due?: string | null;
          parent_approved_at?: string | null;
          notes?: string | null;
          updated_at?: string;
        };
        Update: {
          id?: string;
          order_id?: string | null;
          school_id?: string;
          admission_cycle_id?: string | null;
          status?: Database["public"]["Enums"]["application_status"];
          school_application_no?: string | null;
          submitted_at?: string | null;
          next_action?: string | null;
          next_action_due?: string | null;
          parent_approved_at?: string | null;
          notes?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      audit_log: {
        Row: {
          id: number;
          actor: string | null;
          actor_role: Database["public"]["Enums"]["user_role"] | null;
          action: string;
          entity_table: string | null;
          entity_id: string | null;
          before: Json | null;
          after: Json | null;
          at: string;
        };
        Insert: {
          id?: number;
          actor?: string | null;
          actor_role?: Database["public"]["Enums"]["user_role"] | null;
          action: string;
          entity_table?: string | null;
          entity_id?: string | null;
          before?: Json | null;
          after?: Json | null;
          at?: string;
        };
        Update: {
          id?: number;
          actor?: string | null;
          actor_role?: Database["public"]["Enums"]["user_role"] | null;
          action?: string;
          entity_table?: string | null;
          entity_id?: string | null;
          before?: Json | null;
          after?: Json | null;
          at?: string;
        };
        Relationships: [];
      };
      boards: {
        Row: {
          id: number;
          code: string;
          name_en: string;
          name_hi: string | null;
        };
        Insert: {
          id?: number;
          code: string;
          name_en: string;
          name_hi?: string | null;
        };
        Update: {
          id?: number;
          code?: string;
          name_en?: string;
          name_hi?: string | null;
        };
        Relationships: [];
      };
      children: {
        Row: {
          id: string;
          parent_id: string;
          first_name: string;
          date_of_birth: string;
          target_year: string | null;
          target_class: string | null;
          current_school_text: string | null;
          city_id: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          parent_id: string;
          first_name: string;
          date_of_birth: string;
          target_year?: string | null;
          target_class?: string | null;
          current_school_text?: string | null;
          city_id?: number | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          parent_id?: string;
          first_name?: string;
          date_of_birth?: string;
          target_year?: string | null;
          target_class?: string | null;
          current_school_text?: string | null;
          city_id?: number | null;
          created_at?: string;
        };
        Relationships: [];
      };
      cities: {
        Row: {
          id: number;
          district_id: number;
          name_en: string;
          name_hi: string | null;
          slug: string;
          centroid: unknown | null;
          is_launch: boolean;
        };
        Insert: {
          id?: number;
          district_id: number;
          name_en: string;
          name_hi?: string | null;
          slug: string;
          centroid?: unknown | null;
          is_launch?: boolean;
        };
        Update: {
          id?: number;
          district_id?: number;
          name_en?: string;
          name_hi?: string | null;
          slug?: string;
          centroid?: unknown | null;
          is_launch?: boolean;
        };
        Relationships: [];
      };
      class_levels: {
        Row: {
          code: string;
          sort_order: number;
          label_en: string;
          label_hi: string | null;
        };
        Insert: {
          code: string;
          sort_order: number;
          label_en: string;
          label_hi?: string | null;
        };
        Update: {
          code?: string;
          sort_order?: number;
          label_en?: string;
          label_hi?: string | null;
        };
        Relationships: [];
      };
      consents: {
        Row: {
          id: number;
          user_id: string | null;
          phone: string | null;
          purpose: Database["public"]["Enums"]["consent_purpose"];
          notice_version: string;
          granted_at: string;
          withdrawn_at: string | null;
          channel: string;
        };
        Insert: {
          id?: number;
          user_id?: string | null;
          phone?: string | null;
          purpose: Database["public"]["Enums"]["consent_purpose"];
          notice_version: string;
          granted_at?: string;
          withdrawn_at?: string | null;
          channel: string;
        };
        Update: {
          id?: number;
          user_id?: string | null;
          phone?: string | null;
          purpose?: Database["public"]["Enums"]["consent_purpose"];
          notice_version?: string;
          granted_at?: string;
          withdrawn_at?: string | null;
          channel?: string;
        };
        Relationships: [];
      };
      content_posts: {
        Row: {
          id: string;
          city_id: number | null;
          kind: string;
          language: string;
          payload: Json;
          status: string;
          published_channels: string[] | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          city_id?: number | null;
          kind: string;
          language?: string;
          payload: Json;
          status?: string;
          published_channels?: string[] | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          city_id?: number | null;
          kind?: string;
          language?: string;
          payload?: Json;
          status?: string;
          published_channels?: string[] | null;
          created_at?: string;
        };
        Relationships: [];
      };
      correction_requests: {
        Row: {
          id: string;
          school_id: string | null;
          requester: string;
          kind: string;
          details: string | null;
          status: string;
          created_at: string;
          resolved_at: string | null;
        };
        Insert: {
          id?: string;
          school_id?: string | null;
          requester: string;
          kind: string;
          details?: string | null;
          status?: string;
          created_at?: string;
          resolved_at?: string | null;
        };
        Update: {
          id?: string;
          school_id?: string | null;
          requester?: string;
          kind?: string;
          details?: string | null;
          status?: string;
          created_at?: string;
          resolved_at?: string | null;
        };
        Relationships: [];
      };
      corridors: {
        Row: {
          id: number;
          name: string;
          slug: string;
          aliases: string[];
          centroid: unknown | null;
          name_hi: string | null;
          name_hi_status: string;
        };
        Insert: {
          id?: number;
          name: string;
          slug: string;
          aliases?: string[];
          centroid?: unknown | null;
          name_hi?: string | null;
          name_hi_status?: string;
        };
        Update: {
          id?: number;
          name?: string;
          slug?: string;
          aliases?: string[];
          centroid?: unknown | null;
          name_hi?: string | null;
          name_hi_status?: string;
        };
        Relationships: [];
      };
      data_quality_flags: {
        Row: {
          id: number;
          school_id: string | null;
          source_record_id: number | null;
          rule: string;
          field: string | null;
          detail: string | null;
          resolved: boolean;
          created_at: string;
        };
        Insert: {
          id?: number;
          school_id?: string | null;
          source_record_id?: number | null;
          rule: string;
          field?: string | null;
          detail?: string | null;
          resolved?: boolean;
          created_at?: string;
        };
        Update: {
          id?: number;
          school_id?: string | null;
          source_record_id?: number | null;
          rule?: string;
          field?: string | null;
          detail?: string | null;
          resolved?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      districts: {
        Row: {
          id: number;
          state_id: number;
          name_en: string;
          name_hi: string | null;
          slug: string;
          lgd_code: string | null;
        };
        Insert: {
          id?: number;
          state_id: number;
          name_en: string;
          name_hi?: string | null;
          slug: string;
          lgd_code?: string | null;
        };
        Update: {
          id?: number;
          state_id?: number;
          name_en?: string;
          name_hi?: string | null;
          slug?: string;
          lgd_code?: string | null;
        };
        Relationships: [];
      };
      documents: {
        Row: {
          id: string;
          child_id: string;
          kind: Database["public"]["Enums"]["doc_type"];
          storage_path: string;
          sha256: string;
          uploaded_at: string;
          retain_until: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          child_id: string;
          kind: Database["public"]["Enums"]["doc_type"];
          storage_path: string;
          sha256: string;
          uploaded_at?: string;
          retain_until: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          child_id?: string;
          kind?: Database["public"]["Enums"]["doc_type"];
          storage_path?: string;
          sha256?: string;
          uploaded_at?: string;
          retain_until?: string;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      enquiries: {
        Row: {
          id: string;
          school_id: string;
          user_id: string | null;
          child_id: string | null;
          class_code: string | null;
          message: string | null;
          status: string;
          billable: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          school_id: string;
          user_id?: string | null;
          child_id?: string | null;
          class_code?: string | null;
          message?: string | null;
          status?: string;
          billable?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          school_id?: string;
          user_id?: string | null;
          child_id?: string | null;
          class_code?: string | null;
          message?: string | null;
          status?: string;
          billable?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      events: {
        Row: {
          id: number;
          name: string;
          anon_id: string | null;
          user_id: string | null;
          city_id: number | null;
          school_id: string | null;
          class_code: string | null;
          props: Json | null;
          utm: Json | null;
          at: string;
        };
        Insert: {
          id?: number;
          name: string;
          anon_id?: string | null;
          user_id?: string | null;
          city_id?: number | null;
          school_id?: string | null;
          class_code?: string | null;
          props?: Json | null;
          utm?: Json | null;
          at?: string;
        };
        Update: {
          id?: number;
          name?: string;
          anon_id?: string | null;
          user_id?: string | null;
          city_id?: number | null;
          school_id?: string | null;
          class_code?: string | null;
          props?: Json | null;
          utm?: Json | null;
          at?: string;
        };
        Relationships: [];
      };
      facilities: {
        Row: {
          code: string;
          label_en: string;
          label_hi: string | null;
          category: string | null;
        };
        Insert: {
          code: string;
          label_en: string;
          label_hi?: string | null;
          category?: string | null;
        };
        Update: {
          code?: string;
          label_en?: string;
          label_hi?: string | null;
          category?: string | null;
        };
        Relationships: [];
      };
      featured_placements: {
        Row: {
          id: string;
          school_id: string;
          city_id: number;
          class_codes: string[] | null;
          placement: string;
          starts_on: string;
          ends_on: string;
          label: string;
          order_ref: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          school_id: string;
          city_id: number;
          class_codes?: string[] | null;
          placement: string;
          starts_on: string;
          ends_on: string;
          label?: string;
          order_ref?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          school_id?: string;
          city_id?: number;
          class_codes?: string[] | null;
          placement?: string;
          starts_on?: string;
          ends_on?: string;
          label?: string;
          order_ref?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      fee_items: {
        Row: {
          id: string;
          school_id: string;
          academic_year: string;
          class_code: string | null;
          component: string;
          amount_min: number | null;
          amount_max: number | null;
          frequency: string | null;
          verification: Database["public"]["Enums"]["verification_status"];
          updated_at: string;
        };
        Insert: {
          id?: string;
          school_id: string;
          academic_year: string;
          class_code?: string | null;
          component: string;
          amount_min?: number | null;
          amount_max?: number | null;
          frequency?: string | null;
          verification?: Database["public"]["Enums"]["verification_status"];
          updated_at?: string;
        };
        Update: {
          id?: string;
          school_id?: string;
          academic_year?: string;
          class_code?: string | null;
          component?: string;
          amount_min?: number | null;
          amount_max?: number | null;
          frequency?: string | null;
          verification?: Database["public"]["Enums"]["verification_status"];
          updated_at?: string;
        };
        Relationships: [];
      };
      field_provenance: {
        Row: {
          id: number;
          entity_table: string;
          entity_id: string;
          field: string;
          value: Json | null;
          source_id: number | null;
          source_record_id: number | null;
          evidence_url: string | null;
          verified_by: string | null;
          verified_at: string | null;
          created_at: string;
          licence_class: string;
        };
        Insert: {
          id?: number;
          entity_table: string;
          entity_id: string;
          field: string;
          value?: Json | null;
          source_id?: number | null;
          source_record_id?: number | null;
          evidence_url?: string | null;
          verified_by?: string | null;
          verified_at?: string | null;
          created_at?: string;
          licence_class?: string;
        };
        Update: {
          id?: number;
          entity_table?: string;
          entity_id?: string;
          field?: string;
          value?: Json | null;
          source_id?: number | null;
          source_record_id?: number | null;
          evidence_url?: string | null;
          verified_by?: string | null;
          verified_at?: string | null;
          created_at?: string;
          licence_class?: string;
        };
        Relationships: [];
      };
      form_mappings: {
        Row: {
          id: string;
          school_id: string;
          academic_year: string;
          form_url: string | null;
          mapping: Json;
          notes: string | null;
          updated_at: string;
        };
        Insert: {
          id?: string;
          school_id: string;
          academic_year: string;
          form_url?: string | null;
          mapping: Json;
          notes?: string | null;
          updated_at?: string;
        };
        Update: {
          id?: string;
          school_id?: string;
          academic_year?: string;
          form_url?: string | null;
          mapping?: Json;
          notes?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      invoices: {
        Row: {
          id: string;
          number: string;
          customer_type: string;
          customer_id: string;
          amount_inr: number;
          gst_inr: number;
          gstin: string | null;
          issued_at: string;
          pdf_path: string | null;
        };
        Insert: {
          id?: string;
          number: string;
          customer_type: string;
          customer_id: string;
          amount_inr: number;
          gst_inr: number;
          gstin?: string | null;
          issued_at?: string;
          pdf_path?: string | null;
        };
        Update: {
          id?: string;
          number?: string;
          customer_type?: string;
          customer_id?: string;
          amount_inr?: number;
          gst_inr?: number;
          gstin?: string | null;
          issued_at?: string;
          pdf_path?: string | null;
        };
        Relationships: [];
      };
      landmarks: {
        Row: {
          id: number;
          locality_id: number | null;
          name: string;
          type: string | null;
        };
        Insert: {
          id?: number;
          locality_id?: number | null;
          name: string;
          type?: string | null;
        };
        Update: {
          id?: number;
          locality_id?: number | null;
          name?: string;
          type?: string | null;
        };
        Relationships: [];
      };
      localities: {
        Row: {
          id: number;
          city_id: number;
          name_en: string;
          name_hi: string | null;
          slug: string;
          pincodes: string[] | null;
          centroid: unknown | null;
          notable_landmarks: string[] | null;
          nearby_locality_slugs: string[] | null;
          zone: string | null;
          ward_number: string | null;
          ward_name: string | null;
          character_tags: string[] | null;
          micro_localities: string[] | null;
          description: string | null;
          enrichment_source: string | null;
          aliases: string[];
          parent_locality_id: number | null;
          status: string;
          source: string | null;
          external_ref: string | null;
          name_hi_status: string;
          superseded_by_corridor_id: number | null;
        };
        Insert: {
          id?: number;
          city_id: number;
          name_en: string;
          name_hi?: string | null;
          slug: string;
          pincodes?: string[] | null;
          centroid?: unknown | null;
          notable_landmarks?: string[] | null;
          nearby_locality_slugs?: string[] | null;
          zone?: string | null;
          ward_number?: string | null;
          ward_name?: string | null;
          character_tags?: string[] | null;
          micro_localities?: string[] | null;
          description?: string | null;
          enrichment_source?: string | null;
          aliases?: string[];
          parent_locality_id?: number | null;
          status?: string;
          source?: string | null;
          external_ref?: string | null;
          name_hi_status?: string;
          superseded_by_corridor_id?: number | null;
        };
        Update: {
          id?: number;
          city_id?: number;
          name_en?: string;
          name_hi?: string | null;
          slug?: string;
          pincodes?: string[] | null;
          centroid?: unknown | null;
          notable_landmarks?: string[] | null;
          nearby_locality_slugs?: string[] | null;
          zone?: string | null;
          ward_number?: string | null;
          ward_name?: string | null;
          character_tags?: string[] | null;
          micro_localities?: string[] | null;
          description?: string | null;
          enrichment_source?: string | null;
          aliases?: string[];
          parent_locality_id?: number | null;
          status?: string;
          source?: string | null;
          external_ref?: string | null;
          name_hi_status?: string;
          superseded_by_corridor_id?: number | null;
        };
        Relationships: [];
      };
      locality_corridors: {
        Row: {
          locality_id: number;
          corridor_id: number;
        };
        Insert: {
          locality_id: number;
          corridor_id: number;
        };
        Update: {
          locality_id?: number;
          corridor_id?: number;
        };
        Relationships: [];
      };
      locality_neighbors: {
        Row: {
          locality_id: number;
          neighbor_locality_id: number;
          distance_meters: number | null;
          method: string;
        };
        Insert: {
          locality_id: number;
          neighbor_locality_id: number;
          distance_meters?: number | null;
          method: string;
        };
        Update: {
          locality_id?: number;
          neighbor_locality_id?: number;
          distance_meters?: number | null;
          method?: string;
        };
        Relationships: [];
      };
      locality_pincodes: {
        Row: {
          locality_id: number;
          pincode: string;
        };
        Insert: {
          locality_id: number;
          pincode: string;
        };
        Update: {
          locality_id?: number;
          pincode?: string;
        };
        Relationships: [];
      };
      ops_tasks: {
        Row: {
          id: string;
          kind: Database["public"]["Enums"]["task_type"];
          status: Database["public"]["Enums"]["task_status"];
          priority: number;
          school_id: string | null;
          ref_table: string | null;
          ref_id: string | null;
          assignee: string | null;
          due_at: string | null;
          payload: Json | null;
          outcome: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          kind: Database["public"]["Enums"]["task_type"];
          status?: Database["public"]["Enums"]["task_status"];
          priority?: number;
          school_id?: string | null;
          ref_table?: string | null;
          ref_id?: string | null;
          assignee?: string | null;
          due_at?: string | null;
          payload?: Json | null;
          outcome?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          kind?: Database["public"]["Enums"]["task_type"];
          status?: Database["public"]["Enums"]["task_status"];
          priority?: number;
          school_id?: string | null;
          ref_table?: string | null;
          ref_id?: string | null;
          assignee?: string | null;
          due_at?: string | null;
          payload?: Json | null;
          outcome?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      products: {
        Row: {
          code: string;
          name: string;
          price_inr: number;
          gst_rate: number;
          active: boolean;
        };
        Insert: {
          code: string;
          name: string;
          price_inr: number;
          gst_rate?: number;
          active?: boolean;
        };
        Update: {
          code?: string;
          name?: string;
          price_inr?: number;
          gst_rate?: number;
          active?: boolean;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          user_id: string;
          role: Database["public"]["Enums"]["user_role"];
          full_name: string | null;
          phone: string | null;
          email: string | null;
          language: string;
          home_city_id: number | null;
          created_at: string;
        };
        Insert: {
          user_id: string;
          role?: Database["public"]["Enums"]["user_role"];
          full_name?: string | null;
          phone?: string | null;
          email?: string | null;
          language?: string;
          home_city_id?: number | null;
          created_at?: string;
        };
        Update: {
          user_id?: string;
          role?: Database["public"]["Enums"]["user_role"];
          full_name?: string | null;
          phone?: string | null;
          email?: string | null;
          language?: string;
          home_city_id?: number | null;
          created_at?: string;
        };
        Relationships: [];
      };
      sales_accounts: {
        Row: {
          school_id: string;
          stage: string;
          owner: string | null;
          last_contact_at: string | null;
          notes: string | null;
        };
        Insert: {
          school_id: string;
          stage?: string;
          owner?: string | null;
          last_contact_at?: string | null;
          notes?: string | null;
        };
        Update: {
          school_id?: string;
          stage?: string;
          owner?: string | null;
          last_contact_at?: string | null;
          notes?: string | null;
        };
        Relationships: [];
      };
      sales_activities: {
        Row: {
          id: number;
          school_id: string | null;
          actor: string | null;
          kind: string | null;
          outcome: string | null;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: number;
          school_id?: string | null;
          actor?: string | null;
          kind?: string | null;
          outcome?: string | null;
          notes?: string | null;
          created_at?: string;
        };
        Update: {
          id?: number;
          school_id?: string | null;
          actor?: string | null;
          kind?: string | null;
          outcome?: string | null;
          notes?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      schema_migrations: {
        Row: {
          filename: string;
          applied_at: string;
        };
        Insert: {
          filename: string;
          applied_at?: string;
        };
        Update: {
          filename?: string;
          applied_at?: string;
        };
        Relationships: [];
      };
      school_affiliations: {
        Row: {
          id: string;
          school_id: string;
          board_id: number;
          affiliation_no: string | null;
          level: string | null;
          valid_from: string | null;
          valid_to: string | null;
          source_id: number | null;
        };
        Insert: {
          id?: string;
          school_id: string;
          board_id: number;
          affiliation_no?: string | null;
          level?: string | null;
          valid_from?: string | null;
          valid_to?: string | null;
          source_id?: number | null;
        };
        Update: {
          id?: string;
          school_id?: string;
          board_id?: number;
          affiliation_no?: string | null;
          level?: string | null;
          valid_from?: string | null;
          valid_to?: string | null;
          source_id?: number | null;
        };
        Relationships: [];
      };
      school_claims: {
        Row: {
          id: string;
          school_id: string;
          user_id: string;
          method: string;
          evidence: Json | null;
          status: Database["public"]["Enums"]["claim_status"];
          reviewed_by: string | null;
          reviewed_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          school_id: string;
          user_id: string;
          method: string;
          evidence?: Json | null;
          status?: Database["public"]["Enums"]["claim_status"];
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          school_id?: string;
          user_id?: string;
          method?: string;
          evidence?: Json | null;
          status?: Database["public"]["Enums"]["claim_status"];
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      school_facilities: {
        Row: {
          school_id: string;
          facility_code: string;
          available: boolean;
          notes: string | null;
        };
        Insert: {
          school_id: string;
          facility_code: string;
          available: boolean;
          notes?: string | null;
        };
        Update: {
          school_id?: string;
          facility_code?: string;
          available?: boolean;
          notes?: string | null;
        };
        Relationships: [];
      };
      school_identifiers: {
        Row: {
          school_id: string;
          scheme: string;
          value: string;
        };
        Insert: {
          school_id: string;
          scheme: string;
          value: string;
        };
        Update: {
          school_id?: string;
          scheme?: string;
          value?: string;
        };
        Relationships: [];
      };
      school_media: {
        Row: {
          id: string;
          school_id: string;
          kind: string;
          storage_path: string | null;
          external_url: string | null;
          licence: string;
          approved: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          school_id: string;
          kind: string;
          storage_path?: string | null;
          external_url?: string | null;
          licence: string;
          approved?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          school_id?: string;
          kind?: string;
          storage_path?: string | null;
          external_url?: string | null;
          licence?: string;
          approved?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      school_members: {
        Row: {
          school_id: string;
          user_id: string;
          role: string;
        };
        Insert: {
          school_id: string;
          user_id: string;
          role?: string;
        };
        Update: {
          school_id?: string;
          user_id?: string;
          role?: string;
        };
        Relationships: [];
      };
      school_slug_history: {
        Row: {
          school_id: string;
          city_slug: string;
          old_slug: string;
          changed_at: string;
        };
        Insert: {
          school_id: string;
          city_slug: string;
          old_slug: string;
          changed_at?: string;
        };
        Update: {
          school_id?: string;
          city_slug?: string;
          old_slug?: string;
          changed_at?: string;
        };
        Relationships: [];
      };
      schools: {
        Row: {
          id: string;
          slug: string;
          city_id: number | null;
          locality_id: number | null;
          district_id: number | null;
          name_en: string;
          name_hi: string | null;
          name_search: unknown | null;
          management: Database["public"]["Enums"]["school_management"] | null;
          gender: Database["public"]["Enums"]["school_gender"] | null;
          medium: string[] | null;
          min_class: string | null;
          max_class: string | null;
          address: string | null;
          pincode: string | null;
          location: unknown | null;
          geocode_precision: string | null;
          website: string | null;
          phone: string[] | null;
          email: string[] | null;
          established_year: number | null;
          tier: Database["public"]["Enums"]["school_tier"];
          status: Database["public"]["Enums"]["record_status"];
          verification: Database["public"]["Enums"]["verification_status"];
          claim: Database["public"]["Enums"]["claim_status"];
          completeness: number;
          last_verified_at: string | null;
          next_check_due: string | null;
          about_en: string | null;
          about_hi: string | null;
          created_at: string;
          updated_at: string;
          edudel_zone: string | null;
          corridor_id: number | null;
          locality_assignment_method: string | null;
          locality_assignment_note: string | null;
        };
        Insert: {
          id?: string;
          slug: string;
          city_id?: number | null;
          locality_id?: number | null;
          district_id?: number | null;
          name_en: string;
          name_hi?: string | null;
          name_search?: unknown | null;
          management?: Database["public"]["Enums"]["school_management"] | null;
          gender?: Database["public"]["Enums"]["school_gender"] | null;
          medium?: string[] | null;
          min_class?: string | null;
          max_class?: string | null;
          address?: string | null;
          pincode?: string | null;
          location?: unknown | null;
          geocode_precision?: string | null;
          website?: string | null;
          phone?: string[] | null;
          email?: string[] | null;
          established_year?: number | null;
          tier?: Database["public"]["Enums"]["school_tier"];
          status?: Database["public"]["Enums"]["record_status"];
          verification?: Database["public"]["Enums"]["verification_status"];
          claim?: Database["public"]["Enums"]["claim_status"];
          completeness?: number;
          last_verified_at?: string | null;
          next_check_due?: string | null;
          about_en?: string | null;
          about_hi?: string | null;
          created_at?: string;
          updated_at?: string;
          edudel_zone?: string | null;
          corridor_id?: number | null;
          locality_assignment_method?: string | null;
          locality_assignment_note?: string | null;
        };
        Update: {
          id?: string;
          slug?: string;
          city_id?: number | null;
          locality_id?: number | null;
          district_id?: number | null;
          name_en?: string;
          name_hi?: string | null;
          name_search?: unknown | null;
          management?: Database["public"]["Enums"]["school_management"] | null;
          gender?: Database["public"]["Enums"]["school_gender"] | null;
          medium?: string[] | null;
          min_class?: string | null;
          max_class?: string | null;
          address?: string | null;
          pincode?: string | null;
          location?: unknown | null;
          geocode_precision?: string | null;
          website?: string | null;
          phone?: string[] | null;
          email?: string[] | null;
          established_year?: number | null;
          tier?: Database["public"]["Enums"]["school_tier"];
          status?: Database["public"]["Enums"]["record_status"];
          verification?: Database["public"]["Enums"]["verification_status"];
          claim?: Database["public"]["Enums"]["claim_status"];
          completeness?: number;
          last_verified_at?: string | null;
          next_check_due?: string | null;
          about_en?: string | null;
          about_hi?: string | null;
          created_at?: string;
          updated_at?: string;
          edudel_zone?: string | null;
          corridor_id?: number | null;
          locality_assignment_method?: string | null;
          locality_assignment_note?: string | null;
        };
        Relationships: [];
      };
      seat_status: {
        Row: {
          id: string;
          school_id: string;
          academic_year: string;
          class_code: string;
          public_status: Database["public"]["Enums"]["seat_public_status"];
          range_label: string | null;
          exact_count: number | null;
          confidence: Database["public"]["Enums"]["seat_confidence"];
          mid_session_accepted: boolean | null;
          reported_via: string | null;
          reported_at: string;
          confirmed_at: string | null;
        };
        Insert: {
          id?: string;
          school_id: string;
          academic_year: string;
          class_code: string;
          public_status: Database["public"]["Enums"]["seat_public_status"];
          range_label?: string | null;
          exact_count?: number | null;
          confidence: Database["public"]["Enums"]["seat_confidence"];
          mid_session_accepted?: boolean | null;
          reported_via?: string | null;
          reported_at?: string;
          confirmed_at?: string | null;
        };
        Update: {
          id?: string;
          school_id?: string;
          academic_year?: string;
          class_code?: string;
          public_status?: Database["public"]["Enums"]["seat_public_status"];
          range_label?: string | null;
          exact_count?: number | null;
          confidence?: Database["public"]["Enums"]["seat_confidence"];
          mid_session_accepted?: boolean | null;
          reported_via?: string | null;
          reported_at?: string;
          confirmed_at?: string | null;
        };
        Relationships: [];
      };
      shortlists: {
        Row: {
          user_id: string;
          school_id: string;
          child_id: string | null;
          created_at: string;
        };
        Insert: {
          user_id: string;
          school_id: string;
          child_id?: string | null;
          created_at?: string;
        };
        Update: {
          user_id?: string;
          school_id?: string;
          child_id?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      source_records: {
        Row: {
          id: number;
          source_id: number;
          external_id: string;
          payload: Json;
          content_hash: string;
          fetched_at: string;
          matched_school_id: string | null;
          match_confidence: number | null;
          match_method: string | null;
        };
        Insert: {
          id?: number;
          source_id: number;
          external_id: string;
          payload: Json;
          content_hash: string;
          fetched_at?: string;
          matched_school_id?: string | null;
          match_confidence?: number | null;
          match_method?: string | null;
        };
        Update: {
          id?: number;
          source_id?: number;
          external_id?: string;
          payload?: Json;
          content_hash?: string;
          fetched_at?: string;
          matched_school_id?: string | null;
          match_confidence?: number | null;
          match_method?: string | null;
        };
        Relationships: [];
      };
      sources: {
        Row: {
          id: number;
          code: string;
          name: string;
          base_url: string | null;
          licence_note: string | null;
          trust_rank: number;
        };
        Insert: {
          id?: number;
          code: string;
          name: string;
          base_url?: string | null;
          licence_note?: string | null;
          trust_rank?: number;
        };
        Update: {
          id?: number;
          code?: string;
          name?: string;
          base_url?: string | null;
          licence_note?: string | null;
          trust_rank?: number;
        };
        Relationships: [];
      };
      states: {
        Row: {
          id: number;
          code: string;
          name_en: string;
          name_hi: string | null;
        };
        Insert: {
          id?: number;
          code: string;
          name_en: string;
          name_hi?: string | null;
        };
        Update: {
          id?: number;
          code?: string;
          name_en?: string;
          name_hi?: string | null;
        };
        Relationships: [];
      };
      update_reports: {
        Row: {
          id: string;
          school_id: string | null;
          reporter_type: string;
          reporter_id: string | null;
          contact: string | null;
          message: string;
          attachment_path: string | null;
          status: Database["public"]["Enums"]["review_status"];
          created_at: string;
        };
        Insert: {
          id?: string;
          school_id?: string | null;
          reporter_type: string;
          reporter_id?: string | null;
          contact?: string | null;
          message: string;
          attachment_path?: string | null;
          status?: Database["public"]["Enums"]["review_status"];
          created_at?: string;
        };
        Update: {
          id?: string;
          school_id?: string | null;
          reporter_type?: string;
          reporter_id?: string | null;
          contact?: string | null;
          message?: string;
          attachment_path?: string | null;
          status?: Database["public"]["Enums"]["review_status"];
          created_at?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: {
      current_role_is: {
        Args: Record<string, unknown>; // r user_role
        Returns: unknown; // boolean
      };
      current_user_role: {
        Args: Record<string, unknown>; // no args
        Returns: unknown; // user_role
      };
      fuzzy_candidates_in_districts: {
        Args: Record<string, unknown>; // p_district_ids integer[], p_name text, p_limit integer DEFAULT 5
        Returns: unknown; // TABLE(id uuid, name_en text, address text, pincode text, sim real)
      };
      is_school_member: {
        Args: Record<string, unknown>; // sid uuid
        Returns: unknown; // boolean
      };
      is_staff: {
        Args: Record<string, unknown>; // no args
        Returns: unknown; // boolean
      };
      normalize_school_name: {
        Args: Record<string, unknown>; // input text
        Returns: unknown; // text
      };
      saras_fuzzy_candidates: {
        Args: Record<string, unknown>; // p_district_id integer, p_name text, p_limit integer DEFAULT 5
        Returns: unknown; // TABLE(id uuid, name_en text, sim real)
      };
    };
    Enums: {
      admission_status:
        | "not_announced"
        | "upcoming"
        | "open"
        | "closing_soon"
        | "closed"
        | "results_out";
      application_status:
        | "not_started"
        | "preparing"
        | "awaiting_parent_approval"
        | "submitted"
        | "fee_pending"
        | "interview_scheduled"
        | "result_selected"
        | "result_waitlisted"
        | "result_not_selected"
        | "withdrawn";
      claim_status: "unclaimed" | "pending" | "claimed" | "rejected";
      consent_purpose:
        | "account"
        | "child_profile"
        | "whatsapp_alerts"
        | "application_help"
        | "document_storage"
        | "marketing";
      doc_type:
        | "birth_certificate"
        | "photo_child"
        | "photo_parent"
        | "address_proof"
        | "aadhaar_masked"
        | "previous_report_card"
        | "transfer_certificate"
        | "caste_certificate"
        | "income_certificate"
        | "medical"
        | "other";
      form_mode: "online" | "offline" | "both" | "unknown";
      order_status:
        | "draft"
        | "awaiting_payment"
        | "paid"
        | "in_progress"
        | "completed"
        | "cancelled"
        | "refunded";
      record_status: "draft" | "published" | "hidden" | "closed" | "opt_out";
      review_status: "pending" | "approved" | "edited" | "rejected" | "needs_triage";
      school_gender: "coed" | "boys" | "girls";
      school_management:
        | "private_unaided"
        | "private_aided"
        | "government"
        | "central_government"
        | "local_body"
        | "other";
      school_tier: "A" | "B" | "C";
      seat_confidence: "confirmed" | "reported" | "application_possible";
      seat_public_status: "open" | "limited" | "waitlist" | "closed";
      task_status: "open" | "in_progress" | "blocked" | "done" | "cancelled";
      task_type:
        | "verify_notice"
        | "verify_update"
        | "verify_record"
        | "call_school"
        | "application"
        | "claim_review"
        | "correction_request"
        | "seat_update";
      user_role: "parent" | "school_admin" | "ops" | "admin";
      verification_status: "unverified" | "source_verified" | "ops_verified" | "school_verified";
    };
    CompositeTypes: Record<string, never>;
  };
};
